package com.example.mcp.server;

import static com.example.mcp.server.OrderModels.*;

import org.springframework.ai.mcp.annotation.McpTool;
import org.springframework.ai.mcp.annotation.McpToolParam;
import org.springframework.stereotype.Service;

@Service
public class OrderMcpTools {
    private final OrderRepository repository;

    public OrderMcpTools(OrderRepository repository) {
        this.repository = repository;
    }

    @McpTool(
        name = "orders_get_status",
        description = """
            Retrieve the current fulfillment and delivery status for one order.
            Use only for order progress, shipping, or expected-delivery questions.
            This tool is read-only and must not be used to modify an order.
            """)
    public OrderStatusResult getOrderStatus(
            @McpToolParam(description = "Stable order ID such as ORD-1001", required = true)
            String orderId) {

        RequestIdentity identity = RequestIdentity.demoIdentity();
        return repository.find(identity.tenantId(), orderId)
                .orElseThrow(() -> new IllegalArgumentException("Order not found or not authorized"));
    }

    @McpTool(
        name = "orders_create_replacement",
        description = """
            Create a replacement request for an eligible order. This changes business state.
            The host must obtain explicit user approval before exposing or calling this tool.
            An idempotency key is required to prevent duplicate replacements.
            """)
    public ReplacementResult createReplacement(
            @McpToolParam(description = "Stable order ID", required = true) String orderId,
            @McpToolParam(description = "Reason: DAMAGED, MISSING_ITEM, or DEFECTIVE", required = true)
            ReplacementReason reason,
            @McpToolParam(description = "Unique idempotency key generated by the host", required = true)
            String idempotencyKey) {

        RequestIdentity identity = RequestIdentity.demoIdentity();
        repository.find(identity.tenantId(), orderId)
                .orElseThrow(() -> new IllegalArgumentException("Order not found or not authorized"));
        return repository.createIdempotently(identity.tenantId(), orderId, reason, idempotencyKey);
    }
}
