package com.example.mcp.server;

import static com.example.mcp.server.OrderModels.*;

import org.springframework.ai.mcp.annotation.McpTool;
import org.springframework.ai.mcp.annotation.McpToolParam;
import org.springframework.stereotype.Service;

@Service
public class OrderMcpTools {
    private final OrderService orderService;

    public OrderMcpTools(OrderService orderService) {
        this.orderService = orderService;
    }

    @McpTool(
        name = "orders_get_status",
        description = """
            Retrieve the current fulfillment and delivery status for one order.
            Use only for order progress, shipping, or expected-delivery questions.
            This tool is read-only and must not be used to modify an order.
            """)
    public OrderStatusResult getOrderStatus(
            @McpToolParam(description = "Stable order ID such as ORD-1001", required = true)
            String orderId) {

        return orderService.getOrderStatus(orderId);
    }

    @McpTool(
        name = "orders_create_replacement",
        description = """
            Create a replacement request for an eligible order. This changes business state.
            The host must obtain explicit user approval before exposing or calling this tool.
            An idempotency key is required to prevent duplicate replacements.
            """)
    public ReplacementResult createReplacement(
            @McpToolParam(description = "Stable order ID", required = true) String orderId,
            @McpToolParam(description = "Reason: DAMAGED, MISSING_ITEM, or DEFECTIVE", required = true)
            ReplacementReason reason,
            @McpToolParam(description = "Unique idempotency key generated by the host", required = true)
            String idempotencyKey) {

        return orderService.createReplacement(orderId, reason, idempotencyKey);
    }
}
